//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WLXK.SmartFish.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlData
    {
        public int Id { get; set; }
        public double PhValues { get; set; }
        public double Oxygen { get; set; }
        public double MinTemperate { get; set; }
        public double MaxTemperate { get; set; }
    }
}
