//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WLXK.SmartFish.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiveDatas
    {
        public int Id { get; set; }
        public Nullable<double> EnviroTemperate { get; set; }
        public Nullable<double> EnviroHumidity { get; set; }
        public Nullable<double> SunValue { get; set; }
        public Nullable<double> FishTemperate { get; set; }
        public Nullable<double> Oxygen { get; set; }
        public Nullable<double> PhValues { get; set; }
        public double EnviroTemperate2 { get; set; }
        public double EnviroHumidity2 { get; set; }
        public double SunValue2 { get; set; }
        public double FishTemperate2 { get; set; }
        public System.DateTime SubTime { get; set; }
    }
}
